import { TaskParamType, TaskType, WorkflowTask } from "@/lib/types";
import { Clock, LucideProps } from "lucide-react";

export const ScheduleTriggerTask = {
  type: TaskType.SCHEDULE_TRIGGER,
  label: "Schedule Trigger",
  icon: (props: LucideProps) => (
    <Clock className="stroke-orange-400" {...props} />
  ),
  isEntryPoint: true,
  inputs: [
    {
      name: "Schedule Type",
      type: TaskParamType.SELECT,
      required: true,
      hideHandle: true,
      options: [
        { label: "Once (Single Run)", value: "once" },
        { label: "Daily", value: "daily" },
        { label: "Weekly", value: "weekly" },
        { label: "Monthly", value: "monthly" },
        { label: "Custom Interval", value: "custom" },
      ],
      helperText: "How often should this workflow run?",
    },
    {
      name: "Time",
      type: TaskParamType.SELECT,
      required: true,
      hideHandle: true,
      options: [
        { label: "12:00 AM - 1:00 AM", value: "0" },
        { label: "1:00 AM - 2:00 AM", value: "1" },
        { label: "2:00 AM - 3:00 AM", value: "2" },
        { label: "3:00 AM - 4:00 AM", value: "3" },
        { label: "4:00 AM - 5:00 AM", value: "4" },
        { label: "5:00 AM - 6:00 AM", value: "5" },
        { label: "6:00 AM - 7:00 AM", value: "6" },
        { label: "7:00 AM - 8:00 AM", value: "7" },
        { label: "8:00 AM - 9:00 AM", value: "8" },
        { label: "9:00 AM - 10:00 AM", value: "9" },
        { label: "10:00 AM - 11:00 AM", value: "10" },
        { label: "11:00 AM - 12:00 PM", value: "11" },
        { label: "12:00 PM - 1:00 PM", value: "12" },
        { label: "1:00 PM - 2:00 PM", value: "13" },
        { label: "2:00 PM - 3:00 PM", value: "14" },
        { label: "3:00 PM - 4:00 PM", value: "15" },
        { label: "4:00 PM - 5:00 PM", value: "16" },
        { label: "5:00 PM - 6:00 PM", value: "17" },
        { label: "6:00 PM - 7:00 PM", value: "18" },
        { label: "7:00 PM - 8:00 PM", value: "19" },
        { label: "8:00 PM - 9:00 PM", value: "20" },
        { label: "9:00 PM - 10:00 PM", value: "21" },
        { label: "10:00 PM - 11:00 PM", value: "22" },
        { label: "11:00 PM - 12:00 AM", value: "23" },
      ],
      helperText: "What time should it run?",
    },
    {
      name: "Days of Week",
      type: TaskParamType.SELECT,
      required: false,
      hideHandle: true,
      options: [
        { label: "Monday", value: "1" },
        { label: "Tuesday", value: "2" },
        { label: "Wednesday", value: "3" },
        { label: "Thursday", value: "4" },
        { label: "Friday", value: "5" },
        { label: "Saturday", value: "6" },
        { label: "Sunday", value: "0" },
        { label: "Weekdays (Mon-Fri)", value: "1-5" },
        { label: "Weekends (Sat-Sun)", value: "0,6" },
        { label: "Every Day", value: "*" },
      ],
      helperText: "Which days? (Only for weekly schedule)",
    },
    {
      name: "Specific Date",
      type: TaskParamType.STRING,
      required: false,
      hideHandle: true,
      helperText: "For single run: YYYY-MM-DD (e.g., 2024-01-15)",
    },
    {
      name: "Timezone",
      type: TaskParamType.SELECT,
      required: true,
      hideHandle: true,
      options: [
        { label: "UTC (Coordinated Universal Time)", value: "UTC" },
        { label: "EST (Eastern Standard Time)", value: "America/New_York" },
        { label: "CST (Central Standard Time)", value: "America/Chicago" },
        { label: "MST (Mountain Standard Time)", value: "America/Denver" },
        { label: "PST (Pacific Standard Time)", value: "America/Los_Angeles" },
        { label: "GMT (Greenwich Mean Time)", value: "Europe/London" },
        { label: "CET (Central European Time)", value: "Europe/Paris" },
        { label: "JST (Japan Standard Time)", value: "Asia/Tokyo" },
        { label: "IST (India Standard Time)", value: "Asia/Kolkata" },
        { label: "AEST (Australian Eastern Time)", value: "Australia/Sydney" },
      ],
      helperText: "Your local timezone",
    },
    {
      name: "Custom Cron",
      type: TaskParamType.STRING,
      required: false,
      hideHandle: true,
      helperText: "Advanced: Custom cron expression (e.g., */15 * * * * for every 15 min)",
    },
  ],
  outputs: [
    {
      name: "Timestamp",
      type: TaskParamType.STRING,
      helperText: "Current execution timestamp",
    },
    {
      name: "Schedule Info",
      type: TaskParamType.STRING,
      helperText: "Human-readable schedule description",
    },
  ],
} satisfies WorkflowTask;